Disable -Wshadow warning flag
perl-5.24.0 introduces a flaw in its header files which
breaks with -Wshadow

In file included from /usr/lib64/perl5/CORE/perl.h:5860:0,
                 from Virt.xs:22:
/usr/lib64/perl5/CORE/inline.h: In function ‘S_cx_popsub_args’:
/usr/lib64/perl5/CORE/inline.h:526:19: error: declaration of ‘av’ shadows a previous local [-Werror=shadow]
     CX_POP_SAVEARRAY(cx);
                   ^~
In file included from /usr/lib64/perl5/CORE/perl.h:5860:0,
                 from Virt.xs:22:
/usr/lib64/perl5/CORE/inline.h:518:9: note: shadowed declaration is here
     AV *av;
         ^~
cc1: all warnings being treated as errors

Signed-off-by: Daniel P. Berrange <berrange@redhat.com>